CREATE USER test_user;
ALTER USER test_user WITH PASSWORD 'dummy';
ALTER USER test_user WITH CREATEDB;
CREATE DATABASE test_db ENCODING 'UTF-8';
GRANT ALL PRIVILEGES ON DATABASE test_db TO test_user;
